### ISSUE TITLE
RuntimeError: Configure 'allowAllOutbound' directly on the supplied SecurityGroups.

### ISSUE THREAD

**Issue by fichmann** [aws-samples/rekognition-identity-verification#51]
trying to compile on Amazon Linux latest release, and get this error
jsii.errors.JavaScriptError:
  Error: Configure 'allowAllOutbound' directly on the supplied SecurityGroups.
      at Function.configureVpc (/tmp/jsii-kernel-AWRSnP/node_modules/aws-cdk-lib/aws-lambda/lib/function.js:1:23869)
      at new Function (/tmp/jsii-kernel-AWRSnP/node_modules/aws-cdk-lib/aws-lambda/lib/function.js:1:13114)
      at Kernel._Kernel_create (/tmp/tmphn6t526l/lib/program.js:9127:25)
      at Kernel.create (/tmp/tmphn6t526l/lib/program.js:8798:93)
      at KernelHost.processRequest (/tmp/tmphn6t526l/lib/program.js:10715:36)
      at KernelHost.run (/tmp/tmphn6t526l/lib/program.js:10675:22)
      at Immediate._onImmediate (/tmp/tmphn6t526l/lib/program.js:10676:46)
      at processImmediate (node:internal/timers:466:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/rekognition-identity-verification/app.py", line 33, in <module>
    app = RIVApp()
  File "/root/rekognition-identity-verification/.venv/lib64/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/root/rekognition-identity-verification/app.py", line 31, in __init__
    self.riv_stack = DefaultRivStack(self,riv_stack_name, riv_stack_name=riv_stack_name, env=env)
  File "/root/rekognition-identity-verification/.venv/lib64/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/root/rekognition-identity-verification/infra/topologies.py", line 122, in __init__
    userportal = RivUserPortal(self,'UserPortal', riv_stack=self, sharedStorage=sharedStorage)
  File "/root/rekognition-identity-verification/.venv/lib64/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/root/rekognition-identity-verification/infra/userportal/topology.py", line 29, in __init__
    self.functions = RivUserPortalFunctionSet(self,'Functions',
  File "/root/rekognition-identity-verification/.venv/lib64/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/root/rekognition-identity-verification/infra/userportal/functions/topology.py", line 21, in __init__
    self.compare_faces = RivUserPortalCompareFaces(self,'CompareFaces',
  File "/root/rekognition-identity-verification/.venv/lib64/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/root/rekognition-identity-verification/infra/userportal/functions/definitions.py", line 48, in __init__
    super().__init__(scope, id, riv_stack=riv_stack, subnet_group_name=subnet_group_name, env=env)
  File "/root/rekognition-identity-verification/infra/userportal/functions/definitions.py", line 29, in __init__
    super().__init__(scope, id, riv_stack=riv_stack, subnet_group_name=subnet_group_name, env=env, **kwargs)
  File "/root/rekognition-identity-verification/infra/default_lambda.py", line 79, in __init__
    self.function = lambda_.Function(self,'LambdaFunction',
  File "/root/rekognition-identity-verification/.venv/lib64/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/root/rekognition-identity-verification/.venv/lib64/python3.9/site-packages/aws_cdk/aws_lambda/__init__.py", line 27910, in __init__
    jsii.create(self.__class__, self, [scope, id, props])
  File "/root/rekognition-identity-verification/.venv/lib64/python3.9/site-packages/jsii/_kernel/__init__.py", line 334, in create
    response = self.provider.create(
  File "/root/rekognition-identity-verification/.venv/lib64/python3.9/site-packages/jsii/_kernel/providers/process.py", line 365, in create
    return self._process.send(request, CreateResponse)
  File "/root/rekognition-identity-verification/.venv/lib64/python3.9/site-packages/jsii/_kernel/providers/process.py", line 342, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: Configure 'allowAllOutbound' directly on the supplied SecurityGroups.
Subprocess exited with error 1

**Comment by Sushmithasmurthy** [comment]
comment out this line 92 in default_lambda.py -> allow_all_outbound=True, - this worked for me
